---
haproxy_frontend_port: 80
haproxy_mode: http
haproxy_balance: roundrobin
haproxy_backends:
  - { name: web1, address: 192.168.56.21, port: 80 }
  - { name: web2, address: 192.168.56.22, port: 80 }
